# Generated by Django 4.2.1 on 2023-06-15 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_alter_photo_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='created',
        ),
    ]
