# Generated by Django 4.2.1 on 2023-06-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0003_remove_photo_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
